name: CI

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 16.13.1
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.13.1
  #         cache: "npm"
  #     - name: Install npm dependencies
  #       run: npm ci
  #     - name: Run linter
  #       run: npm run lint:report
  # prettier:
  #   name: Prettier
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 16.13.1
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.13.1
  #         cache: "npm"
  #     - name: Install npm dependencies
  #       run: npm ci
  #     - name: Run prettier check
  #       run: npm run format:report
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: "npm"
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:all
